import csv

def create_csv_file(filename, header, data):
    with open(filename, 'w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(header)
        for row in data:
            writer.writerow(row)
    print(f"Created {filename}")

# Ingredients data
ingredients_data = [
    ['whole wheat spaghetti', 'pasta', 2.50],
    ['organic penne rigate', 'pasta', 2.75],
    ['fresh lasagna sheets', 'pasta', 3.50],
    ['egg noodles', 'egg_pasta', 2.25],
    ['arborio rice', 'risotto_rice', 4.00],
    ['basmati rice', 'long_grain_rice', 3.50],
    ['quinoa', 'ancient_grain', 5.00],
    ['sourdough bread', 'artisan_bread', 3.75],
    ['whole wheat tortillas', 'flatbread', 2.50],
    ['frozen pie crust', 'baking_goods', 4.00],
    ['lean ground beef', 'ground_meat', 5.50],
    ['boneless chicken breasts', 'poultry', 4.75],
    ['ribeye steak', 'beef_cuts', 8.00],
    ['wild caught salmon fillet', 'fish', 9.50],
    ['canned tuna in water', 'canned_fish', 2.50],
    ['jumbo shrimp', 'shellfish', 12.00],
    ['free-range eggs', 'eggs', 3.25],
    ['whole milk', 'milk', 2.80],
    ['heavy cream', 'cream', 3.50],
    ['unsalted butter', 'butter', 3.75],
    ['sharp cheddar cheese', 'cheddar_cheese', 4.50],
    ['fresh mozzarella ball', 'mozzarella_cheese', 3.75],
    ['grated parmesan cheese', 'parmesan_cheese', 5.00],
    ['crumbled feta cheese', 'feta_cheese', 4.50],
    ['whole milk ricotta', 'ricotta_cheese', 3.75],
    ['sour cream', 'cultured_cream', 2.25],
    ['Greek yogurt', 'yogurt', 3.00],
    ['cherry tomatoes', 'tomatoes', 2.50],
    ['roma tomatoes', 'tomatoes', 1.75],
    ['English cucumber', 'cucumbers', 1.25],
    ['iceberg lettuce head', 'lettuce', 1.50],
    ['baby spinach leaves', 'leafy_greens', 3.00],
    ['curly kale bunch', 'leafy_greens', 2.75],
    ['mixed salad greens', 'salad_mix', 3.50],
    ['red bell pepper', 'bell_peppers', 1.50],
    ['green zucchini', 'summer_squash', 1.75],
    ['Italian eggplant', 'eggplant', 2.00],
    ['organic carrots bunch', 'root_vegetables', 2.25],
    ['celery hearts', 'celery', 2.50],
    ['broccoli crowns', 'cruciferous_vegetables', 2.75],
    ['cauliflower head', 'cruciferous_vegetables', 3.00],
    ['russet potatoes', 'potatoes', 1.60],
    ['sweet potatoes', 'root_vegetables', 2.00],
    ['yellow onions', 'onions', 1.00],
    ['garlic bulb', 'garlic', 1.30],
    ['fresh ginger root', 'ginger', 1.50],
    ['white mushrooms', 'mushrooms', 3.50],
    ['frozen green peas', 'frozen_vegetables', 2.00],
    ['sweet corn cobs', 'corn', 1.75],
    ['French green beans', 'green_beans', 2.75],
    ['asparagus bunch', 'asparagus', 3.50],
    ['brussels sprouts', 'cruciferous_vegetables', 3.25],
    ['green cabbage head', 'cabbage', 1.75],
    ['red radishes bunch', 'root_vegetables', 1.50],
    ['golden beets bunch', 'root_vegetables', 2.25],
    ['butternut squash', 'winter_squash', 2.50],
    ['pumpkin', 'winter_squash', 3.00],
    ['leeks bunch', 'alliums', 2.75],
    ['fennel bulb', 'aromatic_vegetables', 2.50],
    ['artichoke hearts', 'artichokes', 4.50],
    ['ripe avocados', 'avocados', 2.50],
    ['lemons', 'citrus_fruits', 1.00],
    ['limes', 'citrus_fruits', 1.10],
    ['navel oranges', 'citrus_fruits', 1.20],
    ['Granny Smith apples', 'apples', 1.60],
    ['ripe bananas', 'bananas', 1.00],
    ['fresh strawberries', 'berries', 3.50],
    ['blueberry punnet', 'berries', 4.00],
    ['raspberry punnet', 'berries', 4.50],
    ['red grapes bunch', 'grapes', 3.00],
    ['seedless watermelon', 'melons', 5.50],
    ['cantaloupe melon', 'melons', 3.75],
    ['fresh pineapple', 'tropical_fruits', 4.00],
    ['ripe mangoes', 'tropical_fruits', 2.50],
    ['freestone peaches', 'stone_fruits', 2.00],
    ['Bartlett pears', 'pears', 2.25],
    ['Italian plums', 'stone_fruits', 2.20],
    ['Bing cherries', 'cherries', 5.50],
    ['golden kiwifruit', 'kiwi', 1.50],
    ['extra virgin olive oil', 'cooking_oils', 6.50],
    ['canola oil', 'cooking_oils', 4.00],
    ['virgin coconut oil', 'cooking_oils', 7.00],
    ['toasted sesame oil', 'flavored_oils', 5.00],
    ['aged balsamic vinegar', 'vinegars', 5.50],
    ['red wine vinegar', 'vinegars', 3.75],
    ['low-sodium soy sauce', 'asian_sauces', 3.00],
    ['Sriracha hot sauce', 'hot_sauces', 2.75],
    ['Dijon mustard', 'mustards', 2.50],
    ['real mayonnaise', 'condiments', 3.25],
    ['organic ketchup', 'condiments', 2.80],
    ['smoky BBQ sauce', 'condiments', 3.50],
    ['basil pesto', 'sauces', 4.50],
    ['fresh salsa', 'sauces', 3.75],
    ['classic hummus', 'dips', 4.00],
    ['guacamole dip', 'dips', 4.25],
    ['tahini paste', 'nut_pastes', 5.00],
    ['clover honey', 'sweeteners', 4.50],
    ['pure maple syrup', 'sweeteners', 7.00],
    ['granulated sugar', 'baking_sugars', 1.50],
    ['light brown sugar', 'baking_sugars', 1.75],
    ['powdered sugar', 'baking_sugars', 2.00],
    ['stevia sweetener', 'sugar_alternatives', 5.00]
]

# Recipes data with categorized ingredients
recipes_data = [
    ['Spaghetti Bolognese', 'pasta ground_meat tomatoes onions garlic cooking_oils herbs'],
    ['Chicken Stir Fry', 'poultry bell_peppers root_vegetables cruciferous_vegetables asian_sauces ginger garlic long_grain_rice'],
    ['Vegetable Curry', 'potatoes cruciferous_vegetables root_vegetables frozen_vegetables cooking_oils curry_powder onions garlic long_grain_rice'],
    ['Caesar Salad', 'lettuce baking_goods parmesan_cheese sauces poultry'],
    ['Mushroom Risotto', 'risotto_rice mushrooms onions garlic cooking_oils vegetable_broth parmesan_cheese'],
    ['Beef Tacos', 'ground_meat flatbread lettuce tomatoes cheddar_cheese cultured_cream condiments'],
    ['Greek Salad', 'cucumbers tomatoes onions feta_cheese cooking_oils citrus_fruits herbs'],
    ['Vegetable Lasagna', 'pasta summer_squash leafy_greens ricotta_cheese mozzarella_cheese tomatoes'],
    ['Grilled Salmon', 'fish citrus_fruits herbs cooking_oils garlic'],
    ['Chicken Parmesan', 'poultry baking_goods parmesan_cheese mozzarella_cheese tomatoes pasta'],
    ['Beef Stir Fry', 'beef_cuts cruciferous_vegetables root_vegetables onions asian_sauces ginger garlic long_grain_rice'],
    ['Caprese Salad', 'tomatoes mozzarella_cheese herbs cooking_oils vinegars'],
    ['Vegetable Soup', 'root_vegetables celery onions potatoes tomatoes vegetable_broth herbs'],
    ['Shrimp Scampi', 'shellfish pasta garlic butter cooking_oils citrus_fruits herbs'],
    ['Beef Stroganoff', 'beef_cuts mushrooms onions cultured_cream beef_broth egg_pasta'],
    ['Vegetable Fried Rice', 'long_grain_rice root_vegetables frozen_vegetables onions eggs asian_sauces garlic ginger'],
    ['Chicken Fajitas', 'poultry bell_peppers onions flatbread cultured_cream cheddar_cheese condiments'],
    ['Eggplant Parmesan', 'eggplant tomatoes mozzarella_cheese parmesan_cheese herbs'],
    ['Tuna Salad', 'canned_fish condiments celery onions citrus_fruits'],
    ['Spinach and Feta Quiche', 'eggs leafy_greens feta_cheese onions baking_goods milk']
]

# Create the CSV files
create_csv_file('ingredients.csv', ['name', 'category', 'price'], ingredients_data)
create_csv_file('recipes.csv', ['name', 'ingredients'], recipes_data)